"use client";
import { KeyboardEvent, useMemo, useState } from "react";

const suites = [
  ["Data grid", "Sorting · filtering · pagination · changing row IDs"],
  ["Complex UI", "Gestures · date picker · autocomplete · editable grid"],
  ["Unstable DOM", "Stale elements · intercepted clicks · lazy content"],
  ["Identity", "Auth methods · sessions · roles · storage"],
  ["REST Assured", "Reusable specifications · schema · response validation"],
  ["API failures", "Headers · parameters · 400–500 negative testing"],
  ["Database & SOAP", "SQL integrity · rollback · WSDL · XSD · faults"],
  ["Quality gates", "Accessibility · visual regression · concurrency · performance"],
  ["Admin authorization & audit", "Permissions · 403 handling · admin-only menus · audit access"],
];

const seedRows = Array.from({ length: 18 }, (_, i) => ({ id: `ROW-${1000 + i * 7}`, customer: ["Sadwika","Maya","Jordan","Ava"][i%4], status: ["Pending","Shipped","Failed"][i%3], total: 24 + i * 3.75 }));

export default function AdvancedLab() {
  const [active,setActive]=useState(0),[filter,setFilter]=useState(""),[page,setPage]=useState(0),[sortAsc,setSortAsc]=useState(true);
  const [result,setResult]=useState("Run a test action to see its observable result."),[role,setRole]=useState("viewer"),[items,setItems]=useState(8);
  const [dragged,setDragged]=useState(false),[cell,setCell]=useState("Pending"),[token,setToken]=useState(1);
  const [portalRole,setPortalRole]=useState("customer"),[portalTheme,setPortalTheme]=useState("light"),[device,setDevice]=useState("desktop"),[delay,setDelay]=useState(0),[toast,setToast]=useState("");
  const rows=useMemo(()=>seedRows.filter(r=>r.customer.toLowerCase().includes(filter.toLowerCase())).sort((a,b)=>(a.total-b.total)*(sortAsc?1:-1)).slice(page*5,page*5+5),[filter,page,sortAsc]);
  async function status(code:number){const started=performance.now();const r=await fetch(`/api/advanced-lab?status=${code}`);const body=await r.json();setResult(`${r.status} ${r.statusText} · ${Math.round(performance.now()-started)}ms · ${JSON.stringify(body)}`)}
  async function auth(kind:string){const options:RequestInit={headers:kind==="api-key"?{"X-API-Key":"qa-lab-key"}:kind==="basic"?{Authorization:`Basic ${btoa("qa:lab")}`}:{Authorization:"Bearer valid-lab-token"}};const r=await fetch("/api/advanced-lab?auth=required",options);setResult(`${kind}: ${r.status} · correlation ${r.headers.get("X-Correlation-ID")}`);document.cookie="orderflow_session=active; path=/";localStorage.setItem("orderflow-role",role)}
  async function soap(fault=false){const r=await fetch("/api/soap-orders",{method:"POST",headers:{"content-type":"text/xml",SOAPAction:"GetOrder"},body:`<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Body><GetOrder>${fault?"FAULT-ORDER":"ADV-2048"}</GetOrder></soap:Body></soap:Envelope>`});setResult(`${r.status} · ${(await r.text()).slice(0,260)}`)}
  async function concurrent(){const start=performance.now();const responses=await Promise.all(Array.from({length:6},()=>fetch("/api/advanced-lab")));setResult(`6 concurrent requests · ${responses.every(r=>r.ok)?"all passed":"failure"} · ${Math.round(performance.now()-start)}ms (threshold 1200ms)`)}
  function keys(e:KeyboardEvent<HTMLInputElement>){if(e.ctrlKey&&e.key==="Enter")setResult("Keyboard shortcut Ctrl+Enter accepted")}
  return <main className="qa-page learning-lab advanced-program">
    <nav className="lab-nav"><a className="mark" href="/">SA<span>.</span></a><div className="lab-page-links"><a href="/qa-lab">QA Lab</a><a className="active" href="/advanced-qa">Advanced QA</a></div><a className="lab-home-button" href="/">Home</a></nav>
    <header className="advanced-hero"><p className="section-label light">Advanced QA page</p><h1>Test beyond<br/><em>the happy path.</em></h1><p>Nine practical suites covering difficult UI behavior, enterprise workflows, service contracts, persistence, security, SOAP, accessibility, and reliability.</p><a className="auth-launch" href="/advanced-qa/auth">Register or sign in to the test portal →</a></header>
    <section className="advanced-layout">
      <aside className="advanced-suite-nav">{suites.map((s,i)=><button key={s[0]} className={active===i?"active":""} onClick={()=>setActive(i)}><span>{String(i+1).padStart(2,"0")}</span><div><strong>{s[0]}</strong><small>{s[1]}</small></div></button>)}</aside>
      <section className="advanced-stage">
        <header><span>Suite {active+1} of 9</span><h2>{suites[active][0]}</h2><p>{suites[active][1]}</p></header>
        {active===0&&<div className="challenge"><div className="tool-row"><input aria-label="Filter customers" placeholder="Filter customer…" value={filter} onChange={e=>{setFilter(e.target.value);setPage(0)}}/><button onClick={()=>setSortAsc(v=>!v)}>Sort total {sortAsc?"↑":"↓"}</button><button onClick={()=>setToken(v=>v+1)}>Regenerate row IDs</button></div><table><thead><tr><th>Dynamic ID</th><th>Customer</th><th>Status</th><th>Total</th></tr></thead><tbody>{rows.map((r,i)=><tr key={`${token}-${r.id}`}><td>{r.id}-{token}</td><td>{r.customer}</td><td>{r.status}</td><td>${r.total.toFixed(2)}</td></tr>)}</tbody></table><div className="pager"><button disabled={!page} onClick={()=>setPage(p=>p-1)}>Previous</button><span>Page {page+1}</span><button disabled={(page+1)*5>=seedRows.filter(r=>r.customer.toLowerCase().includes(filter.toLowerCase())).length} onClick={()=>setPage(p=>p+1)}>Next</button></div></div>}
        {active===1&&<div className="challenge"><div className="gesture-grid"><button draggable onDragStart={()=>setDragged(true)}>Drag order card</button><div onDragOver={e=>e.preventDefault()} onDrop={()=>setResult(dragged?"Drop completed":"Nothing dragged")}>Drop zone</div><button onDoubleClick={()=>setResult("Double-click accepted")}>Double-click</button><button onContextMenu={e=>{e.preventDefault();setResult("Right-click menu opened")}}>Right-click</button></div><div className="control-grid"><label>Delivery date<input type="date"/></label><label>City autocomplete<input list="cities"/><datalist id="cities"><option>Chicago</option><option>Dallas</option><option>Austin</option></datalist></label><label>Custom status<select value={cell} onChange={e=>setCell(e.target.value)}><option>Pending</option><option>Approved</option><option>Rejected</option></select></label><label>Editable grid cell<input value={cell} onChange={e=>setCell(e.target.value)} onKeyDown={keys}/></label></div></div>}
        {active===2&&<div className="challenge"><p>Replace a node to trigger a stale reference, test an intercepted click, then load a virtualized-style list.</p><div className="tool-row"><button key={token} onClick={()=>setToken(v=>v+1)}>Replace this DOM node</button><div className="intercept-wrap"><button onClick={()=>setResult("Underlying click completed")}>Intercepted action</button><span onClick={e=>{e.currentTarget.remove();setResult("Overlay removed; retry the click")}}>Blocking overlay — click to remove</span></div></div><div className="virtual-list">{Array.from({length:items},(_,i)=><p key={i}>Lazy order {i+1}</p>)}</div><button onClick={()=>setItems(v=>v+8)}>Load next 8 items</button></div>}
        {active===3&&<div className="challenge"><div className="tool-row"><button onClick={()=>auth("api-key")}>API key</button><button onClick={()=>auth("basic")}>Basic Auth</button><button onClick={()=>auth("bearer")}>Bearer token</button><button onClick={()=>status(401)}>Expired token</button></div><label>Role<select value={role} onChange={e=>setRole(e.target.value)}><option>viewer</option><option>editor</option><option>admin</option></select></label><div className="permission-box">{role==="admin"?"Admin: view, edit, delete":role==="editor"?"Editor: view and edit":"Viewer: read only"}</div><button onClick={()=>{document.cookie="orderflow_session=; Max-Age=0; path=/";localStorage.removeItem("orderflow-role");setResult("Logged out; cookie and local storage cleared")}}>Logout and clear session</button></div>}
        {active===4&&<div className="challenge"><p>Download a Java starter containing a reusable <code>RequestSpecification</code>, header assertions, query parameters, detailed body assertions, and expired-token validation.</p><pre>{`given().spec(spec).queryParam("region","us")\n.when().get("/advanced-lab")\n.then().statusCode(200)\n  .header("X-Correlation-ID", not(emptyString()))\n  .body("order.id", equalTo("ADV-2048"))\n  .body("schemaVersion", equalTo("1.0"));`}</pre><a className="advanced-download" href="/rest-assured-orderflow.java" download>Download REST Assured starter</a></div>}
        {active===5&&<div className="challenge"><p>Call the live endpoint and validate status, JSON error schema, trace ID, headers, cookies, path/query parameters, and retry guidance.</p><div className="status-grid">{[200,400,401,403,404,409,415,422,429,500].map(code=><button key={code} onClick={()=>status(code)}>{code}</button>)}</div><p><a href="/api/advanced-lab?region=us&status=200" target="_blank">Open live response with query parameters ↗</a></p></div>}
        {active===6&&<div className="challenge split-challenge"><div><h3>Database integrity</h3><pre>{`BEGIN TRANSACTION;\nINSERT INTO orders ...;\nSELECT o.id, c.email FROM orders o\nJOIN customers c ON c.id=o.customer_id;\n-- assert FK, UNIQUE, NOT NULL\nROLLBACK; -- test cleanup`}</pre><ul><li>Relationship and JOIN checks</li><li>Unique, foreign-key, and NOT NULL constraints</li><li>Transaction rollback and cleanup</li></ul></div><div><h3>SOAP service</h3><p><a href="/api/soap-orders" target="_blank">Open practice WSDL ↗</a></p><div className="tool-row"><button onClick={()=>soap()}>Valid SOAP request</button><button onClick={()=>soap(true)}>SOAP Fault</button></div><p>Validate Envelope, namespaces, SOAPAction, XML response, XSD types, and faultcode.</p></div></div>}
        {active===7&&<div className="challenge split-challenge"><div><h3>Accessibility & visual regression</h3><ul><li>Keyboard-only journey and visible focus</li><li>Accessible names, roles, contrast, and landmark audit</li><li>Baseline screenshot at desktop and mobile widths</li><li>Mask dynamic IDs before pixel comparison</li></ul><button onClick={()=>setResult("Accessibility audit: landmarks and labelled controls present")}>Run guided accessibility check</button></div><div><h3>Reliability</h3><button onClick={concurrent}>Run 6 concurrent requests</button><p>Assert all responses pass within 1200ms. For 429, read Retry-After, retry with backoff, and cap attempts.</p><button onClick={()=>status(429)}>Test rate limit + retry header</button></div></div>}
        {active===8&&<div className="challenge enterprise-challenge"><div className="enterprise-toolbar"><label>User role<select value={portalRole} onChange={e=>{setPortalRole(e.target.value);setToast(`Signed in as ${e.target.value}`)}}><option>guest</option><option>customer</option><option>support</option><option>admin</option></select></label><label>Network delay<select value={delay} onChange={e=>setDelay(Number(e.target.value))}><option value="0">Normal</option><option value="1200">Slow — 1.2s</option><option value="3000">Very slow — 3s</option></select></label><button onClick={()=>setPortalTheme(v=>v==="light"?"dark":"light")}>{portalTheme==="light"?"Dark":"Light"} mode</button><button onClick={()=>setDevice(v=>v==="desktop"?"mobile":"desktop")}>{device==="desktop"?"Mobile":"Desktop"} view</button></div><section className={`enterprise-preview ${portalTheme} ${device}`}><header><strong>OrderFlow Enterprise</strong><span>{portalRole.toUpperCase()}</span></header><div className="portal-grid"><aside><button>Orders</button><button>Profile</button>{portalRole==="admin"&&<><button>Users</button><button>Audit logs</button></>}</aside><div><h3>{portalRole==="admin"?"Admin dashboard":"My order dashboard"}</h3>{portalRole==="guest"?<div className="portal-login"><p>Choose a role above to test login and authorization.</p><button onClick={()=>setPortalRole("customer")}>Login as customer</button></div>:<><div className="metric-row"><article><span>Orders</span><strong>24</strong></article><article><span>Failed</span><strong>2</strong></article><article><span>Alerts</span><strong>3</strong></article></div><div className="db-viewer"><h4>Database viewer / joined order records</h4><table><thead><tr><th>Order</th><th>Customer FK</th><th>Status</th></tr></thead><tbody><tr><td>OF-2048</td><td>CUST-77</td><td>Shipped</td></tr><tr><td>OF-2051</td><td>CUST-88</td><td>Pending</td></tr></tbody></table></div><div className="portal-actions"><button onClick={()=>window.setTimeout(()=>setToast("Order saved successfully"),delay)}>Save + toast</button><label>Upload invoice<input type="file"/></label><a href="data:text/plain,Enterprise%20QA%20Report" download="enterprise-report.txt">Download report</a></div>{portalRole!=="admin"&&<button className="forbidden-action" onClick={()=>setToast("403 Forbidden — admin role required")}>Attempt admin action</button>}</>}<div className="wcag-sandbox"><h4>Intentional accessibility defects</h4><p>Find low contrast, an unlabeled input, an empty button, and a skipped heading.</p><span className="low-contrast">Low contrast status</span><input placeholder="No accessible label"/><button aria-label=""></button><h6>Skipped heading level</h6></div></div></div></section>{toast&&<div className="enterprise-toast" role="status">{toast}<button onClick={()=>setToast("")}>×</button></div>}</div>}
        <output className="advanced-result" role="status">{result}</output>
      </section>
    </section>
  </main>
}
