"use client";
import { FormEvent, useEffect, useState } from "react";
type User={username:string;email:string;role:string};
type Audit={id:number;username:string;action:string;result:string;createdAt:string};
export default function AuthLab(){
 const[mode,setMode]=useState<"register"|"login">("register"),[message,setMessage]=useState(""),[busy,setBusy]=useState(false),[user,setUser]=useState<User|null>(null),[events,setEvents]=useState<Audit[]>([]);
 useEffect(()=>{fetch("/api/lab-auth").then(r=>r.ok?r.json():null).then(d=>d&&setUser(d.user))},[]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,f=new FormData(form),invite=new URLSearchParams(window.location.search).get("invite"),action=mode==="register"&&invite?"owner-setup":mode;setBusy(true);setMessage(action==="owner-setup"?"Configuring your owner account…":mode==="register"?"Creating test user…":"Signing in…");try{const r=await fetch("/api/lab-auth",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action,username:f.get("username"),email:f.get("email"),password:f.get("password"),role:f.get("role"),adminCode:invite})});const text=await r.text();let d:{user?:User;error?:string}={};try{d=text?JSON.parse(text):{}}catch{}if(!r.ok){setMessage(d.error||`The server could not complete this request (${r.status}). Please retry.`);return}if(!d.user){setMessage("The account was updated, but the server returned an incomplete confirmation. Please switch to Login.");return}setMessage(`${action==="owner-setup"?"Owner admin configured":mode==="register"?"Registered":"Signed in"} successfully as ${d.user.username}.`);if(mode==="register"){setMode("login");form.reset()}if(mode==="login"){setUser(d.user);window.setTimeout(()=>window.location.assign("/advanced-qa"),900)}}catch{setMessage("The request could not reach the server. Please check your connection and retry.")}finally{setBusy(false)}}
 async function audit(){const r=await fetch("/api/lab-auth?view=audit"),d=await r.json();setMessage(r.ok?`Loaded ${d.events.length} authentication events.`:d.error);if(r.ok)setEvents(d.events)}
 async function logout(){await fetch("/api/lab-auth",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"logout"})});setUser(null);setEvents([]);setMessage("Signed out successfully.")}
 return <main className="qa-page auth-lab"><nav className="lab-nav"><a className="mark" href="/">SA<span>.</span></a><div className="lab-page-links"><a href="/qa-lab">QA Lab</a><a className="active" href="/advanced-qa">Advanced QA</a></div><a className="lab-home-button" href="/">Home</a></nav><header><p className="section-label light">Persistent authentication lab</p><h1>Register. Sign in.<br/><em>Audit access.</em></h1><p>Create test users and validate successful, duplicate, invalid-credential, role-based, session, and logout paths.</p></header>
 <section className="auth-workspace"><div className="auth-card">{user?<><span className="auth-status">Active session</span><h2>Welcome, {user.username}</h2><p>Role: <strong>{user.role}</strong></p><div className="auth-actions">{user.role==="admin"&&<button onClick={audit}>View registration & login audit</button>}<a href="/advanced-qa">Open authorization scenarios</a><button onClick={logout}>Logout</button></div></>:<><div className="auth-tabs"><button className={mode==="register"?"active":""} onClick={()=>setMode("register")} disabled={busy}>Register</button><button className={mode==="login"?"active":""} onClick={()=>setMode("login")} disabled={busy}>Login</button></div><form onSubmit={submit}><label>Username<input name="username" required minLength={3} autoComplete="username" disabled={busy}/></label>{mode==="register"&&<><label>Email<input name="email" type="email" required autoComplete="email" disabled={busy}/></label><label>Test role<select name="role" disabled={busy}><option value="customer">Customer</option><option value="support">Support</option></select></label></>}<label>Password<input name="password" type="password" required minLength={8} autoComplete={mode==="register"?"new-password":"current-password"} disabled={busy}/></label><button type="submit" disabled={busy}>{busy?"Please wait…":mode==="register"?"Create test user":"Sign in"}</button></form></>}<output role="status" aria-live="polite">{message}</output></div>
 <aside className="auth-guide"><h2>Test cases</h2><ol><li>Register a unique username and verify 201.</li><li>Repeat it and verify 409 duplicate.</li><li>Use a wrong password and verify 401.</li><li>Login successfully and verify the session.</li><li>Login as admin and inspect the audit table.</li><li>Logout and verify protected access returns 401.</li></ol><p>Passwords are stored only as one-way hashes. The audit records usernames, actions, results, and timestamps.</p></aside></section>
 {events.length>0&&<section className="auth-audit"><h2>Authentication audit</h2><table><thead><tr><th>Username</th><th>Action</th><th>Result</th><th>Timestamp</th></tr></thead><tbody>{events.map(x=><tr key={x.id}><td>{x.username}</td><td>{x.action}</td><td>{x.result}</td><td>{new Date(x.createdAt).toLocaleString()}</td></tr>)}</tbody></table></section>}</main>
}
