"use client";
import { FormEvent, useState } from "react";
type Order={id:number;customer:string;status:string;totalCents:number};
const tests=[
 {id:"TC-16A",title:"Create order",skill:"POST + database insert",objective:"Create a valid order through the API.",expected:"API returns 201 and the database assigns a durable ID."},
 {id:"TC-16B",title:"Read & failure states",skill:"GET + waits + errors",objective:"Load records under success, delay, and failure conditions.",expected:"Success returns 200, slow waits 1.5 seconds, and error returns 503."},
 {id:"TC-16C",title:"Update order",skill:"PATCH + persistence",objective:"Move a Pending order to Shipped.",expected:"API returns 200 and the updated status survives another GET."},
 {id:"TC-16D",title:"Delete order",skill:"DELETE + empty state",objective:"Remove a test record and reload the collection.",expected:"API returns 204 and the deleted record no longer appears."}
];
export default function ApiDataLab(){
 const[active,setActive]=useState(0),[orders,setOrders]=useState<Order[]>([]),[message,setMessage]=useState("No request sent yet."),[busy,setBusy]=useState(false),[completed,setCompleted]=useState<number[]>([]);
 const done=(i:number)=>setCompleted(v=>v.includes(i)?v:[...v,i]);
 async function load(mode=""){setBusy(true);setMessage("Loading…");const r=await fetch(`/api/test-orders${mode?`?mode=${mode}`:""}`),d=await r.json();setBusy(false);if(!r.ok){setMessage(`${r.status}: ${d.error}`);return}setOrders(d.orders);setMessage(`200 OK: ${d.orders.length} order(s) returned`);done(1)}
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget),r=await fetch("/api/test-orders",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({customer:d.get("customer"),total:Number(d.get("total"))})}),body=await r.json();setMessage(r.ok?`201 Created: order ID ${body.order.id}`:`${r.status}: ${body.error}`);if(r.ok){done(0);e.currentTarget.reset();setOrders(v=>[body.order,...v])}}
 async function update(id:number){const r=await fetch("/api/test-orders",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id,status:"Shipped"})});setMessage(`${r.status} ${r.statusText}: order ${id} updated`);if(r.ok){done(2);await load()}}
 async function remove(id:number){const r=await fetch(`/api/test-orders?id=${id}`,{method:"DELETE"});setMessage(`${r.status} ${r.statusText}: order ${id} deleted`);if(r.ok){done(3);setOrders(v=>v.filter(o=>o.id!==id))}}
 return <main className="qa-page learning-lab" data-testid="api-database-lab">
  <nav className="lab-nav"><a className="mark" href="/qa-lab">SA<span>.</span></a><div><span className="live-dot"/> API + DATABASE TEST SUITE</div><a href="/qa-lab">← QA Lab</a></nav>
  <header className="learning-hero"><div><p className="section-label light">Guided integration testing</p><h1>Test API &<br/><em>database.</em></h1></div><div className="learning-summary"><p>Complete four connected test cases against the live OrderFlow API and persistent database.</p><div className="overall-progress"><span><strong>{completed.length}</strong> of 4 completed</span><div><i style={{width:`${completed.length*25}%`}}/></div><b>{completed.length*25}%</b></div></div></header>
  <section className="lab-workspace"><aside className="case-list"><p className="case-label">Test suite / API regression</p>{tests.map((t,i)=><button key={t.id} className={active===i?"active":""} onClick={()=>setActive(i)}><span className={completed.includes(i)?"done":""}>{completed.includes(i)?"✓":String(i+1).padStart(2,"0")}</span><div><small>{t.id}</small><strong>{t.title}</strong><em>{t.skill}</em></div></button>)}</aside>
  <div className="case-stage"><div className="test-brief"><div><span>Objective</span><p>{tests[active].objective}</p></div><div><span>Expected result</span><p>{tests[active].expected}</p></div></div>
   <section className="product-under-test api-guided-stage"><div className="app-bar"><strong>OrderFlow API Console</strong><span>{tests[active].id}</span></div>
   {active===0&&<form className="checkout-form" onSubmit={create} data-testid="create-order-form"><div className="form-title"><span>1</span><div><h2>Create a database record</h2><p>Submit valid data, then assert status 201 and the generated order ID.</p></div></div><div className="field-grid"><label>Customer<input name="customer" required data-testid="api-customer"/></label><label>Total<input name="total" type="number" min=".01" step=".01" required data-testid="api-total"/></label></div><button className="checkout-button">Send POST request</button></form>}
   {active===1&&<div className="tracking-actions api-actions"><div><h2>Test three GET branches</h2><p>Verify normal data, a deterministic slow response, and a controlled service failure.</p><div className="network-buttons"><button onClick={()=>load()} disabled={busy}>GET success</button><button onClick={()=>load("slow")} disabled={busy}>GET slow</button><button onClick={()=>load("error")} disabled={busy}>GET 503</button></div></div></div>}
   {(active===2||active===3)&&<div className="api-records"><div className="tracking-actions"><div><h2>{active===2?"Update a persisted record":"Delete and verify absence"}</h2><p>Load records, then use the action on one row.</p></div><button onClick={()=>load()} disabled={busy}>Load database records</button></div><table><thead><tr><th>ID</th><th>Customer</th><th>Status</th><th>Total</th><th>Action</th></tr></thead><tbody>{orders.map(o=><tr key={o.id} data-testid={`order-${o.id}`}><td>{o.id}</td><td>{o.customer}</td><td>{o.status}</td><td>${(o.totalCents/100).toFixed(2)}</td><td>{active===2?<button onClick={()=>update(o.id)}>PATCH to Shipped</button>:<button onClick={()=>remove(o.id)}>DELETE order</button>}</td></tr>)}</tbody></table>{!orders.length&&<p className="empty-state">No records loaded.</p>}</div>}
   <output className="api-response" role="status" data-testid="api-result">{message}</output></section>
  </div></section>
 </main>
}
